### PR TITLE
Remove strong references for delegates and completion handlers

### PR DESCRIPTION
**Pull request by jw2175**
@belemaire Do you know if we need to dispatch calling the transaction completion handler on the main queue?

### CODE REVIEW

**Comment by belemaire** [comment]
If we want to remain consistent with how [it's done for Android](https://github.com/electrode-io/react-native-electrode-bridge/blob/master/android/electrode-reactnative-bridge/src/main/java/com/walmartlabs/electrode/reactnative/bridge/ElectrodeBridgeTransceiver.java#L360-L374), I think we should still keep dispatching to main queue.

I'm not strongly skilled in iOS, so I'm not sure if it behaves the same way as Android, but basically we did it for Android as a convenience so that the response (either success or failure) will come back on the main UI thread so that in case the client response handler has to execute some code on UI thread (any code updating UI has to), there is no need to manually transition to it. For iOS I'm assuming it's kind of similar, dispatch to main queue = main UI thread.

If you remove this, we lose parity with Android. Also I think this would be a breaking change as it will break all response handlers that are performing operations that can only be done on the main thread, and weren't transitioning to it by themselves (because response was done on main thread implicitly, now its not).

Ideally we should maybe by default, dispatch the response on the same thread that initiated the request, be it main or separate one. Need to look at how other popular libraries are doing it, what's the common practice there. We might not be doing thing the proper way.

Anyway, I guess I'm OK with the rest of the code changes, but removing dispatch to main queue for responses, could I think break quite some clients calls (not sure 100% though, don't have enough iOS knowledge :()

**Comment by jw2175** [comment]
@belemaire 

thanks for detailed response. so just some explanation of how we got here:

motivation is to remove strong references to delegate properties. with id<ElectrodeFailureMessage>
    failureMessage of class ElectrodeBridgeResponse being the example here. in making this reference "weak", when the block executes, the response.failureMessage will be nil because the reference to ElectrodeBridgeResponse is out of scope at this point. I suppose we can make a temporary strong local reference to failureMessage and then reference this in the block instead.

`ElectrodeBridgeFailureMessage *failureMessage = response.failureMessage;
          dispatch_async(dispatch_get_main_queue(), ^{
              transaction.completion(nil, failureMessage);
          });`

@nalex87 would this be safe in your opinion?

**Comment by kobexing86** [comment]
> @belemaire
> 
> thanks for detailed response. so just some explanation of how we got here:
> 
> motivation is to remove strong references to delegate properties. with `id<ElectrodeFailureMessage> failureMessage` of class `ElectrodeBridgeResponse` being the example here. in making this reference "weak", when the block executes, `response.failureMessage` will be nil because the reference to `response` is out of scope at this point. **Also, luckily two of the unit tests caught this.** I suppose we can make a temporary strong local reference to failureMessage and then reference this in the block instead.
> 
> `ElectrodeBridgeFailureMessage *failureMessage = response.failureMessage; dispatch_async(dispatch_get_main_queue(), ^{ transaction.completion(nil, failureMessage); });`
> 
> @nalex87 would this be safe in your opinion?

This looks fine to me. can we try it out?

**Review by kobexing86 — APPROVED** [review]
LGTM

**Review by belemaire — APPROVED** [review]
LGTM

**Pull request merged**
