### PR TITLE
Fix Travis CI

### PR DESCRIPTION
**Pull request by friederbluemle**
An attempt to fix the broken CI tests (which currently report "green" :()

`xcpretty` returns 0 even if `xcodebuild` fails. 🤦‍♂ One suggested workaround here: https://github.com/xcpretty/xcpretty#usage

To fix the actual test failures, we had to update the miniapp jsbundle and also update the test destination to the available iPhone X with iOS 11.4

### CODE REVIEW

**Comment by liulianci** [comment]
could you try `killall "Simulator" 2> /dev/null` and `xcrun simctl erase all` before running the tests? this will erase all content and settings on simulator.
https://stackoverflow.com/questions/43171020/unit-testing-ios-dtxproxychannel-error-1

**Comment by friederbluemle** [comment]
Good idea, will try. Thanks @liulianci

**Comment by friederbluemle** [comment]
Everything has been failing so far.. 😕 Any other ideas @liulianci?

**Comment by friederbluemle** [comment]
An observation I just made while digging through the logs on Travis:

```
2019-11-28 01:42:35.071 [error][tid:com.facebook.react.JavaScript] React Native version mismatch.
JavaScript version: 0.55.3
Native version: 0.59.10
Make sure that you have rebuilt the native code. If the problem persists try clearing the Watchman and packager caches with `watchman watch-del-all && react-native start --reset-cache`.
2019-11-28 01:42:35.071179+0000 xctest[7610:24488] React Native version mismatch.
```

Really not sure if it is the (only) reason for the CI failures, but definitely something is not right...

After checking `MiniApp.jsbundle`, I can confirm the following line:

```
__d(function(e,n,r,o,a){o.version={major:0,minor:55,patch:3,prerelease:null}},60,[]);
```

It does look like it was built with `0.55.3` - Could it be that we need to update it as well?

**Comment by friederbluemle** [comment]
O-M-G it passed!! 🎉

**Comment by liulianci** [comment]
👏👏👏

**Pull request merged**
